POST https://0roolpkdy5.execute-api.us-east-1.amazonaws.com/lead/
content-type: application/json
authorization: Bearer 16d7a4fca7442dda3ad93c9a726597e4

{
"AgencyId": "94c7ef1a-6514-4079-b985-da80f183933c",
"Lead": 
    {
    "firstName": "Wiximo77",
    "lastName": "Wiximo77",
    "leadEmails": ["email@gmail.com"],
    "leadPhones": ["3331113333"],
    "products": ["5d60d928-041a-45df-ae17-2a2947600df4"]
    }
}