const States = [
	{name: "Aguascalientes", sulg: "aguascalientes"},
	{name: "Baja California", sulg: "baja-california"},
	{name: "baja-california-sur", sulg: "Baja California Sur"},
	{name: "Campeche", sulg: "campeche"},
	{name: "Chiapas", sulg: "chiapas"},
	{name: "Chihuahua", sulg: "chihuahua"},
	{name: "Ciudad de México", sulg: "ciudad-de-mexico"},
	{name: "Chiapas", sulg: "chiapas"},
	{name: "Coahuila", sulg: "coahuila"},
	{name: "Colima", sulg: "colima"},
	{name: "Durango", sulg: "durango"},
	{name: "Estado de México", sulg: "estado-de-mexico"},
	{name: "Guanajuato", sulg: "guanajuato"},
	{name: "Guerrero", sulg: "guerrero"},
	{name: "Hidalgo", sulg: "hidalgo"},
	{name: "Jalisco", sulg: "jalisco"},
	{name: "Michoacán", sulg: "michoacan"},
	{name: "Morelos", sulg: "morelos"},
	{name: "Nayarit", sulg: "nayarit"},
	{name: "Nuevo León", sulg: "nuevo-leon"},
	{name: "Oaxaca", sulg: "oaxaca"},
	{name: "Puebla", sulg: "puebla"},
	{name: "Querétaro", sulg: "queretaro"},
	{name: "Quintana Roo", sulg: "san-luis-potosi"},
	{name: "Sinaloa", sulg: "sinaloa"},
	{name: "Sonora", sulg: "sonora"},
	{name: "Tabasco", sulg: "tabasco"},
	{name: "Tamaulipas", sulg: "tamaulipas"},
	{name: "Tlaxcala", sulg: "tlaxcala"},
	{name: "Veracruz", sulg: "veracruz"},
	{name: "Yucatán", sulg: "yucatan"},
	{name: "Zacatecas", sulg: "zacatecas"},
];

export default States;
